services:
   wlldb:
     image: ${DOCKER_REGISTRY}mariadb:latest
     volumes:
       - wll_db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: winlogonlimiter
       MYSQL_USER: timeuser
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
       TZ: America/Denver
     secrets:
       - db_root_password
       - db_password
     healthcheck:
       #test: mysql -uroot -p$$(< /run/secrets/db_root_password) --database=winlogonlimiter -e "SHOW TABLES;" || exit 1
       test:  ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect",  "--innodb_initialized"]
       interval: 10s
       timeout: 5s
       retries: 5
     restart: unless-stopped

   wllweb:
     depends_on:
       wlldb:
         condition: service_healthy
     image: ${DOCKER_IMAGE:-win-logon-limiter:latest}
     ports:
       - "${WEB_PORT:-80}:80"
     environment:
       WLL_DB_PASSWORD_FILE: /run/secrets/db_password
       WLL_JWT_SECRET_FILE: /run/secrets/web_jwt_secret
       WLL_JC_API_KEY_FILE: /run/secrets/web_jc_api_key
       TZ: America/Denver
     secrets:
       - db_password
       - web_jwt_secret
       - web_jc_api_key
     restart: unless-stopped
  
   wllcron:
     depends_on:
       wlldb:
         condition: service_healthy
     image: ${DOCKER_IMAGE_CRON:-win-logon-limiter-cron:latest}
     environment:
       WLL_DB_PASSWORD_FILE: /run/secrets/db_password
       WLL_SSH_KNOWN_HOSTS_FILE: /run/secrets/ssh_known_hosts
       WLL_SSH_PRIVATE_KEY_FILE: /run/secrets/ssh_private_key
       WLL_ROUTER_IP: 192.168.1.1
       TZ: America/Denver
     secrets:
       - db_password
       - ssh_known_hosts
       - ssh_private_key
     restart: unless-stopped

secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt
   ssh_known_hosts:
     file: ssh_known_hosts.txt
   ssh_private_key:
     file: ssh_private_key.txt
   web_jwt_secret:
     file: web_jwt_secret.txt
   web_jc_api_key:
     file: web_jc_api_key.txt

volumes:
    wll_db_data:

# docker-compose -f docker_compose.yml up -d
