services:
   wlldb:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: winlogonlimiter
       MYSQL_USER: timeuser
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_root_password
       - db_password

   wllweb:
     depends_on:
       - wlldb
     image: win-logon-limiter:latest
     ports:
       - "8000:80"
     environment:
       WLL_DB_HOST: wlldb:3306
       WLL_DB_USER: timeuser
       WLL_DB_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_password


secrets:
   db_password:
     file: db_password.txt
   db_root_password:
     file: db_root_password.txt

volumes:
    db_data:

# docker compose -f docker_compose.yml up -d