services:
   composer:
     image: composer:latest
     volumes:
      - .:/app
     environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
     restart: never

   phpunit:
     image: php:bookworm
     restart: never
     volumes:
       - .:/app
     working_dir: /app
     entrypoint: vendor/bin/phpunit



# 
# docker-compose -f docker_compose.yml run composer require --dev phpunit/phpunit
# docker-compose -f docker_compose.yml run phpunit --generate-configuration
# docker-compose -f docker_compose.yml run phpunit --colors=never --log-junit phpunit-index-report.xml tests
