#!/bin/sh
set -e

# Update passsword file
DB_PASSWORD=$(cat /run/secrets/db_password)
sed -i "s/##DB_PASSWORD##/$DB_PASSWORD/g" /var/www/password.php

# Update db if needed
/tools/dbupdater/update_db.php

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"