services:
   composer:
     image: composer:latest
     volumes:
      - .:/app
     environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
     restart: never

   phpunit:
     image: php:bookworm
     restart: never
     volumes:
       - .:/app
     working_dir: /app
     entrypoint: vendor/bin/phpunit



# 
# docker-compose -f phpunit/docker-compose-tests.yml run --rm composer require --dev phpunit/phpunit
# docker-compose -f phpunit/docker-compose-tests.yml run --rm phpunit --generate-configuration
# docker-compose -f phpunit/docker-compose-tests.yml run --rm phpunit --colors=never --log-junit phpunit-report.xml phpunit/tests
